# Generated by Django 3.1.7 on 2021-09-03 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_auto_20210901_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='social.post'),
        ),
    ]
